name: Build and push Docker image to dockerhub

on:
  push:
    branches: ["main"]

env:
  COG_REPO: "fofr"
  COG_MODEL: "any-comfyui-workflow"
  COG_VERSION: "f552cf6bb263b2c7c547c3c7fb158aa4309794934bedc16c9aa395bee407744d"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Login to dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Remove unnecessary files
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"

      - name: Build and push to dockerhub
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/fofr-any-comfyui-workflow:latest
          build-args: |
            COG_REPO=${{ env.COG_REPO }}
            COG_MODEL=${{ env.COG_MODEL }}
            COG_VERSION=${{ env.COG_VERSION }}
